Config

Usage:
  golangci-lint config [flags]
  golangci-lint config [command]

Available Commands:
  path        Print used config path

Flags:
  -h, --help   help for config

Global Flags:
      --color string              Use color when printing; can be 'always', 'auto', or 'never' (default "auto")
  -j, --concurrency int           Concurrency (default NumCPU) (default 8)
      --cpu-profile-path string   Path to CPU profile output file
      --mem-profile-path string   Path to memory profile output file
      --trace-path string         Path to trace output file
  -v, --verbose                   verbose output
      --version                   Print version

Use "golangci-lint config [command] --help" for more information about a command.
