name: golangci-lint
on:
  push:
    # tags:
    #   - v*
    branches:
      - main
      - master
      - dev
  pull_request:
jobs:
  golangci:
    strategy:
      matrix:
        go-version: [1.18.x]
        os: [ubuntu-latest]
    name: lint
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Install vips
        run: |
          sudo add-apt-repository -y ppa:strukturag/libde265
          sudo add-apt-repository -y ppa:strukturag/libheif
          sudo add-apt-repository ppa:tonimelisma/ppa
          sudo apt-get update
          sudo apt-get install -y libvips-dev
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3.4.0
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.52.2
          # Optional: working directory, useful for monorepos
          # working-directory: somedir

          # Optional: golangci-lint command line arguments.
          # args: config > .golangci.yml

          # Optional: show only new issues if it's a pull request. The default value is `false`.
          # only-new-issues: true
