name: go-test

on:
  push:
    # tags:
    #   - v*
    branches:
      - main
      - master
      - dev
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        go-version: ['1.18', '1.19', '1.20.x']
        os: [ubuntu-latest]
    name: ${{ matrix.go-version }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Display Go version
        run: go version

      - name: Install vips
        run: |
          sudo apt-get update
          sudo apt-get install -y libvips-dev

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Build
        run: go build -v ./...

      - name: Run tests
        run: go test -v ./...

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3.4.0
        with:
          version: v1.53.3
